YoshithaRathnayake/CALCULATOR-WEBSITE

index.html

Add the topic

---

index.html

Add a sentence

---

index.html

Add the image

---

index.html

Aligned center the topic

---

index.html

Centered the image of calculator as pointed out using center tag.

 Align the image to center

---

assets/css/styles.css

updated the font size the of main title on styles.css

Updates styles.css by increasing the main title's font size and gave a margin to the title and paragraph

---

assets/css/styles.css
index.html

The paragraph font was slightly increased , as the issue required .
This resolves issue #18 .

Increased the paragraph font a little bit .

---

assets/css/styles.css
index.html

The font-weight of the paragraph has been slightly decreased , as was required .
This resolves issue #22 .

Decreased the font weight of the paragraph a little bit

---

assets/css/styles.css
index.html

Aligned the download button to center of the screen.
Fixes #27 
❤Thankyou!

fix: align the download button to center

---

index.html

I have added the class attribute( as big-calculator) for the img tag which was initially missing.

Added the class attribute for the img tag

---

assets/css/styles.css
index.html

Added new class named "title" to the tag containing title text and replaced the Bootstrap class "text-center" in the CSS stylesheet with "title" class .

Added new class named "title" to the header and replaced the Bootstrap class "text-center" in the CSS stylesheet with "title" class .

---

index.html

Fixed the Download Icon inside the download button

Fixed the Download Icon inside the download button

---

index.html

I have added the div tag with its id as 'button'. It wraps the anchor tag containing the download button.

Added the div tag

---

assets/css/styles.css
index.html

As described in the issue i have deleted the .big-calculator class from css and html and modified the download button in the  middle

Removed the .big-calculator class

---

index.html

There were two download buttons on the website. 
The icon inside the one download button has been fixed and other download button has been removed.

Fixed the icon inside download button and removed the other button

---

assets/css/styles.css
index.html

Added edo font in title

---

.vscode/settings.json
assets/css/styles.css

Changed header to italic style

Italic the heading

---

.vscode/settings.json
assets/css/styles.css
index.html

Fixed the header, as per issue.

Remove the "| YOSHITHA" part from the heading

---

assets/css/styles.css

I have made suitable change. Please merge it

Make the title margin 10px to 10vh

---

index.html

Changed the title of this page as CALCULATOR | YOSHITHA as required.

Changed the title of this page as required

---

assets/css/styles.css
index.html

A new hover effect has been added to the download button on the page.

Added hover effect to the Download button.

---

assets/css/styles.css
index.html

The bold from font style property in .title class of css file has been removed.

Removed the bold from font style property in .title class of css file

---

assets/css/styles.css

CSS styling of the page heading ahs been modified so as to make it stand out from the Page background .
This is how the heading now looks ...

Changed the style of the page heading so as to make it stand out from the Page background .

---

assets/css/styles.css

Remove background colour from paragraph. Changed text colour for visibility.

Remove the background color of the paragraph

---

assets/css/styles.css

The color of the heading has been changed to #26eab9 as required .

Changed heading color as required .

---

assets/css/styles.css
index.html

please let me know if there are any changes.

Increase the heading font size

---

index.html

Removed the "| YOSHITHA" part from the heading and changed the title to CALCULATOR.

Changed the title of the page to CALCULATOR

---

index.html

Changed the description a little bit.

Changed the description a little bit.

---

assets/css/styles.css

increase blur for paragraph background

---

index.html

Removed the doubled paragraph - Fix issue #134

Removed doubled paragraph

---

assets/css/styles.css
index.html

Hi there,
I appreciate the opportunity to contribute.

Download button from id to class

---

README.md

The purpose of this Pull Request is to fix #152 
https://github.com/kheersagar/CALCULATOR-WEBSITE?organization=kheersagar&organization=kheersagar

added js logo in readme.md file

---

README.md

The purpose of this Pull Request is to fix #151
Yaml logo links to yaml tutorial by Tutorialspoint

Added the yaml logo to README file

---

README.md
assets/css/styles.css
index.html

Hi there,
I hope it is okay that I have created this pull request without getting assigned yet.

Remove dash

---

README.md

Updated Readme file with :
Used Programming Languages (HTML, CSS, and BOOTSTRAP)

Change the sentence in readme.md file

---

README.md

The purpose of this Pull Request is to fix #168 
Adding YAML in used programming languages section
https://github.com/Roxie2003/CALCULATOR-WEBSITE/blob/30a1b39d7934e45d996f6daf99d5ab0cbd06d940/README.md

Add yaml in used programming languages

---

README.md

Added the word "python" in used programming languages.
The purpose of this Pull Request is to fix #169

Add python for the readme.md file

---

.github/pull_request_template.md

Add a new comment for the Preview Link section in PR Template

Add a new comment for the Preview Link section in PR Template

---

README.md

Add javascript to the readme.md file

Add javascript to the readme.md file

---

assets/css/styles.css

Change text selection colors

---

assets/css/styles.css

Add color variables

---

index.html

Fix the alignments in the navbar

Fix the alignments in the navbar

---

assets/css/styles.css
assets/js/app.js
index.html

Format the code

---

index.html

Change the navbar code position

Change the navbar code position

---

assets/css/styles.css

Remove unwanted codes from styles.css file

Remove unwanted codes from styles.css file

---

assets/css/styles.css
index.html

Make the download button class as download-btn in both index.html and styles.css file

Make the download button class as download-btn in both index.html and styles.css file

---

index.html

Increase the margin of the download button

Increase the margin of the download button

---

index.html

Make the calculator image class as cal-img in both index.html and styles.css file

Make the calculator image class as cal-img in both index.html and styles.css file

---

assets/css/styles.css

Make the header sticky

---

assets/css/styles.css

Blur the background of the navbar

Blur the background of the navbar

---

index.html

The main heading and the nav is sticked

The main heading and the nav is sticked

---

assets/css/styles.css

Add a scroll bar
https://pr-216-CALCULATOR-WEBSITE.surge.sh/

Add a scroll bar

---

assets/css/styles.css

Increase the height of the navbar
fix #217

Increase the height of the navbar

---

assets/css/styles.css

Align the nav links correctly
fix #223

Align the nav links correctly

---

assets/css/styles.css

Align the title correctly
fix #225

Align the title correctly

---

index.html

Change the download link
fix #227

Change the download link

---

README.md

Add app downloading section to the readme file
fix #229

Add app downloading section to the readme file

---

README.md

The purpose of this Pull Request is to fix #232
Align the calculator interface image center
Aligned the calculator interface image center
https://github.com/Prasadkpd/CALCULATOR-WEBSITE/tree/alignCalImage

Align the calculator interface image center
